import Head from 'next/head'
import Navbar from '@/Components/Navbar'
import Footer from '@/Components/Footer'



export default function Home() {
return (
<>
<Head>
<title>Chick-a-licious</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
</Head>



<Navbar/>
<h1>Home </h1>
<Footer/>
</>
)
}
