import Head from 'next/head'
import Navbar from '@/Components/Navbar'
import Footer from '@/Components/Footer'
import Card from '@/Components/Menu/Card'
import fs from 'fs';
import path from 'path'
import matter from 'gray-matter'


export default function Home({posts}) {
return (
<>
<Head>
<title>Chick-a-licious</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
</Head>



<Navbar/>

<div className='card-grid'>
{posts && posts.map((post, index) => (
<Card key={index} post={post}/>
))}
</div>


<Footer/>
</>
)
}

export async function getStaticProps() {
// Get files from the feartered articles dir
const files = await fs.promises.readdir('Menu');
  
// Get slug and frontmatter from blogs
const posts = await Promise.all(
files.map(async (filename) => {
// Create slug
const slug = filename.replace('.md', '');
  
// Get frontmatter
const markdownWithMeta = await fs.promises.readFile(
path.join('Menu', filename),
'utf-8');
  
const { data: frontmatter } = matter(markdownWithMeta);
return {
slug,
frontmatter,
};
})
);
// articles block

posts.sort((a, b) => new Date(a.frontmatter.date) - new Date(b.frontmatter.date));
  
return {
props: {
posts,


},
};
}